indicators:
  bollinger_bands:
    period: 20
    std_dev: 2
  ema:
    period: 20
  rsi:
    period: 14
strategy:
  rsi_overbought: 70
  rsi_oversold: 30
watchlist:
- AAPL
- GOOGL
- MSFT
- TSLA
- NVDA

# Data fetching defaults (leave interval null for daily data)
data_fetching:
  max_data_period: "max"  # "max" for inception, or specific period like "10y"
  # Intraday support: set interval to '60m' for hourly bars (default null = daily)
  interval: 60m
  # For intraday use shorter fallback periods (example shown commented):
  fallback_periods: ["max", "10y", "5y", "2y", "1y", "6mo", "3mo", "1mo"]
  # If using intraday, reduce min threshold because long history isn't available
  min_data_threshold: 200  # Minimum records required (adjust for intraday)
  timeout_per_symbol: 600000   # Timeout for data fetching
  show_data_summary: true  # Show data range information
