# NIFTY 500 Configuration
data_sources:
  yahoo_finance:
    enabled: true
    rate_limit: 3  # Slower rate for large number of symbols

# Data fetching configuration
data_fetching:
  max_data_period: "max"  # "max" for inception, or specific period like "10y"
  fallback_periods: ["max", "10y", "5y", "2y", "1y", "6mo"]
  min_data_threshold: 200  # Minimum days of data required
  timeout_per_symbol: 60   # Timeout for data fetching
  show_data_summary: true  # Show data range information

# NIFTY 500 stocks (partial list - top performing stocks)
watchlist:
  # Large Cap
  - "RELIANCE.NS"
  - "TCS.NS"
  - "HDFCBANK.NS"
  - "INFY.NS"
  - "HINDUNILVR.NS"
  - "ICICIBANK.NS"
  - "KOTAKBANK.NS"
  - "SBIN.NS"
  - "BHARTIARTL.NS"
  - "ITC.NS"
  - "ASIANPAINT.NS"
  - "LT.NS"
  - "AXISBANK.NS"
  - "MARUTI.NS"
  - "SUNPHARMA.NS"
  - "TITAN.NS"
  - "ULTRACEMCO.NS"
  - "WIPRO.NS"
  - "NESTLEIND.NS"
  - "POWERGRID.NS"
  - "NTPC.NS"
  - "HCLTECH.NS"
  - "BAJFINANCE.NS"
  - "M&M.NS"
  - "TECHM.NS"
  - "TATAMOTORS.NS"
  - "COALINDIA.NS"
  - "TATASTEEL.NS"
  - "ADANIPORTS.NS"
  - "ONGC.NS"
  - "INDUSINDBK.NS"
  - "JSWSTEEL.NS"
  - "GRASIM.NS"
  - "HINDALCO.NS"
  - "CIPLA.NS"
  - "DRREDDY.NS"
  - "EICHERMOT.NS"
  - "UPL.NS"
  - "APOLLOHOSP.NS"
  - "BAJAJFINSV.NS"
  - "DIVISLAB.NS"
  - "HDFCLIFE.NS"
  - "SBILIFE.NS"
  - "BRITANNIA.NS"
  - "SHREECEM.NS"
  - "HEROMOTOCO.NS"
  - "BAJAJ-AUTO.NS"
  - "GODREJCP.NS"
  - "PIDILITIND.NS"
  - "DABUR.NS"
  
  # Mid Cap
  - "ADANIGREEN.NS"
  - "ADANIENT.NS"
  - "ADANITRANS.NS"
  - "AUROPHARMA.NS"
  - "BANKBARODA.NS"
  - "BERGEPAINT.NS"
  - "BIOCON.NS"
  - "BOSCHLTD.NS"
  - "BPCL.NS"
  - "CADILAHC.NS"
  - "CANBK.NS"
  - "CHOLAFIN.NS"
  - "COLPAL.NS"
  - "CONCOR.NS"
  - "CUMMINSIND.NS"
  - "DLF.NS"
  - "ESCORTS.NS"
  - "EXIDEIND.NS"
  - "FEDERALBNK.NS"
  - "GAIL.NS"
  - "GODREJPROP.NS"
  - "HAVELLS.NS"
  - "HDFC.NS"
  - "HDFCAMC.NS"
  - "IBULHSGFIN.NS"
  - "ICICIPRULI.NS"
  - "IDEA.NS"
  - "IDFCFIRSTB.NS"
  - "INDIGO.NS"
  - "IOC.NS"
  - "IRCTC.NS"
  - "JINDALSTEL.NS"
  - "JUBLFOOD.NS"
  - "L&TFH.NS"
  - "LICHSGFIN.NS"
  - "LUPIN.NS"
  - "MARICO.NS"
  - "MCDOWELL-N.NS"
  - "MFSL.NS"
  - "MOTHERSUMI.NS"
  - "MPHASIS.NS"
  - "MRF.NS"
  - "MUTHOOTFIN.NS"
  - "NMDC.NS"
  - "NAUKRI.NS"
  - "OBEROIRLTY.NS"
  - "OFSS.NS"
  - "PAGEIND.NS"
  - "PETRONET.NS"
  - "PFC.NS"
  - "PIIND.NS"
  - "PNB.NS"
  - "POLYCAB.NS"
  - "PVR.NS"
  - "RAMCOCEM.NS"
  - "RECLTD.NS"
  - "SAIL.NS"
  - "SIEMENS.NS"
  - "SRF.NS"
  - "TORNTPHARM.NS"
  - "TRENT.NS"
  - "TVSMOTOR.NS"
  - "VEDL.NS"
  - "VOLTAS.NS"
  - "ZEEL.NS"
  
  # Small Cap (Selected)
  - "3MINDIA.NS"
  - "AAVAS.NS"
  - "ABB.NS"
  - "ABCAPITAL.NS"
  - "ABFRL.NS"
  - "ACC.NS"
  - "ADANIPOWER.NS"
  - "AFFLE.NS"
  - "AJANTPHARM.NS"
  - "AKZOINDIA.NS"
  - "ALKEM.NS"
  - "AMARAJABAT.NS"
  - "AMBUJACEM.NS"
  - "APOLLOTYRE.NS"
  - "ASHOKLEY.NS"
  - "ASTRAL.NS"
  - "ATUL.NS"
  - "AUBANK.NS"
  - "BALKRISIND.NS"
  - "BALRAMCHIN.NS"
  - "BANDHANBNK.NS"
  - "BATAINDIA.NS"
  - "BEL.NS"
  - "BHARATFORG.NS"
  - "BHEL.NS"
  - "CANFINHOME.NS"
  - "CASTROLIND.NS"
  - "CCL.NS"
  - "CEATLTD.NS"
  - "CENTURYTEX.NS"
  - "CERA.NS"
  - "CHAMBLFERT.NS"
  - "CHENNPETRO.NS"
  - "CHOLAHLDNG.NS"
  - "COFORGE.NS"
  - "COROMANDEL.NS"
  - "CROMPTON.NS"
  - "CUB.NS"
  - "CYIENT.NS"
  - "DEEPAKNTR.NS"
  - "DELTACORP.NS"
  - "DHANUKA.NS"
  - "DIXON.NS"
  - "DMART.NS"
  - "EIDPARRY.NS"
  - "EIHOTEL.NS"
  - "EMAMILTD.NS"
  - "ENDURANCE.NS"
  - "ENGINERSIN.NS"
  - "EQUITAS.NS"
  - "ERIS.NS"
  - "FINEORG.NS"
  - "FLUOROCHEM.NS"
  - "FORTIS.NS"
  - "FSL.NS"
  - "GICRE.NS"
  - "GILLETTE.NS"
  - "GLAXO.NS"
  - "GLENMARK.NS"
  - "GMRINFRA.NS"
  - "GNFC.NS"
  - "GODFRYPHLP.NS"
  - "GRANULES.NS"
  - "GRAPHITE.NS"
  - "GREAVESCOT.NS"
  - "GRINDWELL.NS"
  - "GSFC.NS"
  - "GSPL.NS"
  - "GUJALKALI.NS"
  - "GUJGASLTD.NS"
  - "HAL.NS"
  - "HAPPSTMNDS.NS"
  - "HATSUN.NS"
  - "HCC.NS"
  - "HEG.NS"
  - "HEIDELBERG.NS"
  - "HEXAWARE.NS"
  - "HFCL.NS"
  - "HINDZINC.NS"
  - "HONAUT.NS"
  - "HUDCO.NS"
  - "IBREALEST.NS"
  - "IDBI.NS"
  - "IDFC.NS"
  - "IFBIND.NS"
  - "IIFL.NS"
  - "INDHOTEL.NS"
  - "INDIACEM.NS"
  - "INDIAMART.NS"
  - "INDIANB.NS"
  - "INDOCO.NS"
  - "INFIBEAM.NS"
  - "INOXLEISUR.NS"
  - "INTELLECT.NS"
  - "IOB.NS"
  - "IPCALAB.NS"
  - "IRB.NS"
  - "ISEC.NS"
  - "ITDC.NS"
  - "ITI.NS"
  - "JBCHEPHARM.NS"
  - "JCHAC.NS"
  - "JKCEMENT.NS"
  - "JKLAKSHMI.NS"
  - "JKPAPER.NS"
  - "JMFINANCIL.NS"
  - "JSL.NS"
  - "JSWENERGY.NS"
  - "JUSTDIAL.NS"
  - "JYOTHYLAB.NS"
  - "KAJARIACER.NS"
  - "KANSAINER.NS"
  - "KEI.NS"
  - "KNRCON.NS"
  - "KRBL.NS"
  - "LALPATHLAB.NS"
  - "LAURUSLABS.NS"
  - "LAXMIMACH.NS"
  - "LEMONTREE.NS"
  - "LINDEINDIA.NS"
  - "LTI.NS"
  - "LTTS.NS"
  - "LUXIND.NS"
  - "LXCHEM.NS"
  - "MANAPPURAM.NS"
  - "MASFIN.NS"
  - "MAXHEALTH.NS"
  - "MCX.NS"
  - "METROPOLIS.NS"
  - "MINDACORP.NS"
  - "MINDTREE.NS"
  - "MIDHANI.NS"
  - "MOIL.NS"
  - "MOTILALOFS.NS"
  - "MRPL.NS"
  - "NATCOPHARM.NS"
  - "NATIONALUM.NS"
  - "NAVINFLUOR.NS"
  - "NBCC.NS"
  - "NCC.NS"
  - "NETWORK18.NS"
  - "NHPC.NS"
  - "NIITLTD.NS"
  - "NLCINDIA.NS"
  - "NOCIL.NS"
  - "NRBBEARING.NS"
  - "NUCLEUS.NS"
  - "OIL.NS"
  - "OMAXE.NS"
  - "ORIENTBANK.NS"
  - "PARAGMILK.NS"
  - "PERSISTENT.NS"
  - "PFIZER.NS"
  - "PGHH.NS"
  - "PHOENIXLTD.NS"
  - "PNBHOUSING.NS"
  - "POLYMED.NS"
  - "PRSMJOHNSN.NS"
  - "PTC.NS"
  - "QUESS.NS"
  - "RADICO.NS"
  - "RAIN.NS"
  - "RAJESHEXPO.NS"
  - "RALLIS.NS"
  - "RBLBANK.NS"
  - "REDINGTON.NS"
  - "RELAXO.NS"
  - "RELCAPITAL.NS"
  - "RELINFRA.NS"
  - "RNAM.NS"
  - "ROUTE.NS"
  - "RPOWER.NS"
  - "RSYSTEMS.NS"
  - "RTNINDIA.NS"
  - "SANOFI.NS"
  - "SBICARD.NS"
  - "SCHAEFFLER.NS"
  - "SCHNEIDER.NS"
  - "SCI.NS"
  - "SFL.NS"
  - "SHANKARA.NS"
  - "SHILPAMED.NS"
  - "SHOPERSTOP.NS"
  - "SHRIRAMFIN.NS"
  - "SIS.NS"
  - "SJVN.NS"
  - "SKFINDIA.NS"
  - "SOBHA.NS"
  - "SOLARINDS.NS"
  - "SONATSOFTW.NS"
  - "SOUTHBANK.NS"
  - "SPANDANA.NS"
  - "SPARC.NS"
  - "SPICEJET.NS"
  - "SRTRANSFIN.NS"
  - "STARCEMENT.NS"
  - "STLTECH.NS"
  - "SUDARSCHEM.NS"
  - "SUNDARMFIN.NS"
  - "SUNDRMFAST.NS"
  - "SUNTV.NS"
  - "SUPRAJIT.NS"
  - "SUPREMEIND.NS"
  - "SUVEN.NS"
  - "SWANENERGY.NS"
  - "SYMPHONY.NS"
  - "SYNDIBANK.NS"
  - "SYNGENE.NS"
  - "TAKE.NS"
  - "TATACHEM.NS"
  - "TATACOMM.NS"
  - "TATACONSUM.NS"
  - "TATAELXSI.NS"
  - "TATAPOWER.NS"
  - "TEAMLEASE.NS"
  - "THERMAX.NS"
  - "THOMASCOOK.NS"
  - "THYROCARE.NS"
  - "TIFHL.NS"
  - "TIMKEN.NS"
  - "TORNTPOWER.NS"
  - "TRIDENT.NS"
  - "TRITURBINE.NS"
  - "TTKPRESTIG.NS"
  - "TV18BRDCST.NS"
  - "UBL.NS"
  - "UJJIVAN.NS"
  - "UNIONBANK.NS"
  - "UTTAMSUGAR.NS"
  - "VAIBHAVGBL.NS"
  - "VARROC.NS"
  - "VBL.NS"
  - "VENKEYS.NS"
  - "VGUARD.NS"
  - "VINATIORGA.NS"
  - "VIPIND.NS"
  - "VTL.NS"
  - "WABAG.NS"
  - "WELCORP.NS"
  - "WELSPUNIND.NS"
  - "WESTLIFE.NS"
  - "WHIRLPOOL.NS"
  - "WOCKPHARMA.NS"
  - "YESBANK.NS"
  - "ZENSARTECH.NS"
  - "ZYDUSWELL.NS"

indicators:
  rsi:
    period: 14
  bollinger_bands:
    period: 20
    std_dev: 2
  ema:
    period: 20

strategy:
  swing_trading:
    rsi_oversold: 30
    rsi_overbought: 70

scheduling:
  update_interval: 600  # 10 minutes for large dataset
  market_hours_only: true

output:
  csv_file: "nifty500_signals.csv"
  database: "nifty500_trading_data.db"
  charts_enabled: false
  output_dir: "output"

logging:
  level: "INFO"
  file: "nifty500_trading_bot.log"
  max_size_mb: 50
  backup_count: 10